### ISSUE TITLE
Conflicting and vague installation instructions complicate deployment

### ISSUE THREAD

**Issue by jpodivin** [robertobucher/pysimCoder#57]
Installation procedure described in [README.md](https://github.com/robertobucher/pysimCoder#installation) doesn't specify versions of individual dependencies, duplicates installation of certain system packages, like `python-scipy`, in ubuntu_dependency_installer.py and in manual procedure, while leaving others, like `gfortran` in only one. 

Several of the packages, like already mentioned `python-scipy`, were at some point renamed to `python3-*`, reflecting new version of the python runtime used, and are no longer available under the original name in many distros[0], including recent releases of popular Fedora and Ubuntu distros. Additional, older [README](https://github.com/robertobucher/pysimCoder/blob/master/README) file, with different instructions is also an issue.

All things considered, current state of the instructions leads to unnecessary confusion and loss of time on the side of new users.
Potentially deterring contributors that would be otherwise interested in the project.

To improve the situation I'd propose one of the following changes.

1. Rewrite instructions to have a single list of dependencies and ensure that all are installed in minimum number of commands.
2. Specify, at least, minimum viable version of the dependencies and OS.
3. Create requirements.txt file, listing packages, constraints and licenses for packages installed using `pip`.
4. (Slightly more complicated) rewrite the repo to use poetry[1] packaging and publish the package on PiPy repo.

I'd be willing to tackle points 1. trough 4. personally. With a view that rewriting the repo to use poetry might prove not prove worthwhile, depending on exploration of the option. 

[0] https://pkgs.org/search/?q=python-scipy
[1] https://python-poetry.org/

**Comment by robertobucher** [comment]
You're right, because from the first version of pysimCoder, a lot is changed!

Basically, the python files are the same but as python3-xxxxx.

Ypi can get the Makefile under my repository "LinuxLabo" where you should have the right packages for all the required files: this file should allow to install the required packages under Ubntu to.

If you actualie the installation files, it is welcome, and can be integrate as new PR.

Thanks in advance

Roberto

**Comment by jpodivin** [comment]
Great. I'll take a look at the makefile and propose changes with updated dependencies and guide.

**Comment by robertobucher** [comment]
Thanks!
